# Generated by Django 5.0.7 on 2024-07-16 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact_no', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('cibil_score', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_status', models.CharField(max_length=50)),
                ('loan_term', models.IntegerField(help_text='Loan term in years')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('residential_assets', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commercial_assets', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
