# Generated by Django 5.0.7 on 2024-07-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_application_ml_prediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='age',
            new_name='no_of_dependents',
        ),
        migrations.RemoveField(
            model_name='application',
            name='commercial_assets',
        ),
        migrations.RemoveField(
            model_name='application',
            name='income',
        ),
        migrations.RemoveField(
            model_name='application',
            name='residential_assets',
        ),
        migrations.AddField(
            model_name='application',
            name='bank_asset_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='application',
            name='commercial_assets_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='education',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], default=1),
        ),
        migrations.AddField(
            model_name='application',
            name='income_annum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='application',
            name='luxury_assets_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='application',
            name='residential_assets_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='application',
            name='employment_status',
            field=models.IntegerField(),
        ),
    ]
