# Generated by Django 5.0.7 on 2024-07-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_rename_age_application_no_of_dependents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='employment_status',
            field=models.IntegerField(default=1),
        ),
    ]
